[package]
name = "from-regex-macros"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
heck = "0.3"
lazy_static = "1.4"
proc-macro2 = "1"
quote = "1"
regex = "1.5"
syn = { version = "1", features = ["full"] }